name: Update gist with Douban RSS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "15 8 * * *"

jobs:
  build:
    name: Update-gist
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GIST_ID: ${{ secrets.GIST_ID }}
      DOUBAN_USER: ${{ secrets.DOUBAN_USER }}

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Update-gist
        run: go run ./cmd/main.go
