name: Update gist with Douban RSS

on:
  push:
    branches:
      - master
  schedule:
    - cron: '15 8 * * *'

jobs:
  build:
    name: Update-gist
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GIST_ID: ${{ secrets.GIST_ID }}
      DOUBAN_USER: ${{ secrets.DOUBAN_USER }}
      TIMEZONE: 'Asia/Shanghai'

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: ^1.20
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Update-gist
        run: go run ./cmd/main.go
